# Generated by Django 4.1.1 on 2022-09-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=32)),
                ('duration', models.TimeField()),
                ('banner_url', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('rating', models.CharField(max_length=8)),
                ('language', models.CharField(max_length=32)),
                ('subtitle', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('legal_document', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('format', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theater.person')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('seat_amount', models.IntegerField()),
                ('room', models.CharField(max_length=32)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theater.movie')),
            ],
        ),
    ]
