# Generated by Django 4.1.1 on 2022-09-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiere',
            fields=[
                ('premiere_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theater.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theater.movie')),
            ],
        ),
    ]
